
import java.awt.Image;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Administrator
 */
public class DoTransactionForm extends javax.swing.JInternalFrame {

    DefaultTableModel dtm = new DefaultTableModel(){

        @Override
        public boolean isCellEditable(int row, int column) {
            return super.isCellEditable(row, column);
        }
        
        
    };
    DefaultTableModel dm2 = new DefaultTableModel();
    
    LoginForm log = new LoginForm();
    Koneksi kon = new Koneksi();
    Vector atas,isi;
    ResultSet rs;
    DefaultTableModel dm = new DefaultTableModel();
    int jml =0;
    int jml2 =0;
    int stk = 0;
    int [] stk2 = new int[100];
    Object [][] data = null;
    String [] namakolom = new String[3];
    int temp = 0;
    int trId;
    //membuat tabel pertama
    private void tabel(){
    try{
            //mengambil data dari ms product
            rs = kon.exec("SELECT * FROM MsProduct");
            //mengisi baris
            isi = kon.getVec1();
            //mengisi kolom
            atas = new Vector();
            atas.add("ProductID");
            atas.add("Product Name");
            atas.add("Product Detail");
            atas.add("Product Price");
            atas.add("Product Stock ");
            dm.setDataVector(isi,atas);
            jTable1.setModel(dm);
        }catch(Exception e){
            
        }
    }
    private void tabelList(){
        //mengisi kolom
        namakolom = new String[] {"product","price","quantity" };
        data = new Object[0][3];
        jTable2.setModel(new DefaultTableModel(data,namakolom));
                
    }
    public DoTransactionForm() {
        try {
            initComponents();
           tabel();
           tabelList();
           normalcondition();
           cmbCustomer.insertItemAt(null, 0);
           
           
           //mengambil customer id dari database customer
           ResultSet rs = kon.exec("Select CustomerID from MsCustomer");
           while (rs.next()){
               cmbCustomer.addItem(rs.getString(1));
           }
           
           //menggenerate transaction ID
           ResultSet rs2 = kon.exec("Select * From HeaderTransaction ORDER BY TransactionID Desc ");
           
           if ( rs2.next()){
               trId = Integer.parseInt(rs2.getString(1).substring(2));
           }
        } catch (SQLException ex) {
            Logger.getLogger(DoTransactionForm.class.getName()).log(Level.SEVERE, null, ex);
            trId = 0;
        }
        trId ++;
        //memasukanya ke dalam angka 000
        String newId ="";
        if(trId >=1 && trId<=9){
            newId = "TR00"+trId;
        }else if(trId>=10 && trId <= 99){
            newId = "TR0"+trId;
        }else if(trId>=100 && trId <= 999){
            newId = "TR"+trId;
        }
        txtTransaction.setText(newId);
        
        
        //merubah forma tanggal
        DateFormat dateFm = new SimpleDateFormat("dd/MM/yyyy");
        Date date = new Date();
        //menginput tanggal ke textfield
        txtDate.setText(dateFm.format(date));
        //menginput employee id ke textfield
        txtEmployee.setText(LoginForm.user);
        
        
    }
 //kondisi pertama kali form dijalankan
public void normalcondition(){
    txtDate.setEnabled(false);
    txtEmployee.setEnabled(false);
    txtProductid.setEnabled(false);
    txtTransaction.setEnabled(false);
}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        txtTransaction = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtEmployee = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        cmbCustomer = new javax.swing.JComboBox();
        jLabel5 = new javax.swing.JLabel();
        txtDate = new javax.swing.JTextField();
        jPanel5 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jPanel10 = new javax.swing.JPanel();
        lblImage = new javax.swing.JLabel();
        jPanel11 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        txtProductid = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        txtProductname = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        spinQuantity = new javax.swing.JSpinner();
        butAdd = new javax.swing.JButton();
        butRemove = new javax.swing.JButton();
        jPanel8 = new javax.swing.JPanel();
        jPanel12 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jPanel13 = new javax.swing.JPanel();
        gakguna = new javax.swing.JPanel();
        gakguna2 = new javax.swing.JPanel();
        gakguna3 = new javax.swing.JPanel();
        jPanel16 = new javax.swing.JPanel();
        butBuy = new javax.swing.JButton();
        jPanel17 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jPanel9 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setPreferredSize(new java.awt.Dimension(780, 610));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Tunga", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 51, 255));
        jLabel1.setText("Do Transaction");
        jPanel1.add(jLabel1);

        getContentPane().add(jPanel1, java.awt.BorderLayout.NORTH);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new java.awt.BorderLayout());

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setPreferredSize(new java.awt.Dimension(328, 60));
        jPanel4.setLayout(new java.awt.GridLayout(2, 4));

        jLabel2.setForeground(new java.awt.Color(51, 51, 255));
        jLabel2.setText("Transaction ID");
        jPanel4.add(jLabel2);
        jPanel4.add(txtTransaction);

        jLabel3.setForeground(new java.awt.Color(51, 51, 255));
        jLabel3.setText("Employee ID");
        jPanel4.add(jLabel3);
        jPanel4.add(txtEmployee);

        jLabel4.setForeground(new java.awt.Color(51, 51, 255));
        jLabel4.setText("Customer ID");
        jPanel4.add(jLabel4);

        jPanel4.add(cmbCustomer);

        jLabel5.setForeground(new java.awt.Color(51, 51, 255));
        jLabel5.setText("Transaction Date");
        jPanel4.add(jLabel5);

        txtDate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDateActionPerformed(evt);
            }
        });
        jPanel4.add(txtDate);

        jPanel2.add(jPanel4, java.awt.BorderLayout.NORTH);

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));
        jPanel5.setLayout(new java.awt.BorderLayout());

        jScrollPane1.setPreferredSize(new java.awt.Dimension(452, 200));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jTable1.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jPanel5.add(jScrollPane1, java.awt.BorderLayout.CENTER);

        jPanel2.add(jPanel5, java.awt.BorderLayout.CENTER);

        getContentPane().add(jPanel2, java.awt.BorderLayout.CENTER);

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setMinimumSize(new java.awt.Dimension(764, 100));
        jPanel3.setPreferredSize(new java.awt.Dimension(764, 180));
        jPanel3.setLayout(new java.awt.BorderLayout());

        jPanel7.setBackground(new java.awt.Color(255, 255, 255));
        jPanel7.setPreferredSize(new java.awt.Dimension(764, 150));
        jPanel7.setLayout(new java.awt.GridLayout(1, 0, 8, 0));

        jPanel6.setBackground(new java.awt.Color(255, 255, 255));
        jPanel6.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel6.setLayout(new java.awt.GridLayout(1, 0));

        jPanel10.setBackground(new java.awt.Color(255, 255, 255));
        jPanel10.setLayout(new java.awt.BorderLayout());
        jPanel10.add(lblImage, java.awt.BorderLayout.CENTER);

        jPanel6.add(jPanel10);

        jPanel11.setBackground(new java.awt.Color(255, 255, 255));
        jPanel11.setLayout(new java.awt.GridLayout(4, 2, 5, 5));

        jLabel8.setForeground(new java.awt.Color(0, 0, 255));
        jLabel8.setText("Product Id");
        jPanel11.add(jLabel8);
        jPanel11.add(txtProductid);

        jLabel9.setForeground(new java.awt.Color(0, 0, 255));
        jLabel9.setText("Product Name");
        jPanel11.add(jLabel9);
        jPanel11.add(txtProductname);

        jLabel10.setForeground(new java.awt.Color(0, 0, 255));
        jLabel10.setText("Quantity");
        jPanel11.add(jLabel10);

        spinQuantity.setModel(new javax.swing.SpinnerNumberModel(Integer.valueOf(0), Integer.valueOf(0), null, Integer.valueOf(1)));
        spinQuantity.setPreferredSize(new java.awt.Dimension(29, 23));
        jPanel11.add(spinQuantity);

        butAdd.setForeground(new java.awt.Color(0, 0, 255));
        butAdd.setText("Add To Cart");
        butAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butAddActionPerformed(evt);
            }
        });
        jPanel11.add(butAdd);

        butRemove.setForeground(new java.awt.Color(0, 0, 255));
        butRemove.setText("Remove");
        butRemove.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butRemoveActionPerformed(evt);
            }
        });
        jPanel11.add(butRemove);

        jPanel6.add(jPanel11);

        jPanel7.add(jPanel6);

        jPanel8.setBackground(new java.awt.Color(255, 255, 255));
        jPanel8.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel8.setLayout(new java.awt.GridLayout(1, 0));

        jPanel12.setLayout(new java.awt.BorderLayout());

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane3.setViewportView(jTable2);

        jPanel12.add(jScrollPane3, java.awt.BorderLayout.CENTER);

        jPanel8.add(jPanel12);

        jPanel13.setLayout(new java.awt.GridLayout(5, 1));

        gakguna.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout gakgunaLayout = new javax.swing.GroupLayout(gakguna);
        gakguna.setLayout(gakgunaLayout);
        gakgunaLayout.setHorizontalGroup(
            gakgunaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 187, Short.MAX_VALUE)
        );
        gakgunaLayout.setVerticalGroup(
            gakgunaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 29, Short.MAX_VALUE)
        );

        jPanel13.add(gakguna);

        gakguna2.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout gakguna2Layout = new javax.swing.GroupLayout(gakguna2);
        gakguna2.setLayout(gakguna2Layout);
        gakguna2Layout.setHorizontalGroup(
            gakguna2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 187, Short.MAX_VALUE)
        );
        gakguna2Layout.setVerticalGroup(
            gakguna2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 29, Short.MAX_VALUE)
        );

        jPanel13.add(gakguna2);

        gakguna3.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout gakguna3Layout = new javax.swing.GroupLayout(gakguna3);
        gakguna3.setLayout(gakguna3Layout);
        gakguna3Layout.setHorizontalGroup(
            gakguna3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 187, Short.MAX_VALUE)
        );
        gakguna3Layout.setVerticalGroup(
            gakguna3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 29, Short.MAX_VALUE)
        );

        jPanel13.add(gakguna3);

        jPanel16.setBackground(new java.awt.Color(255, 255, 255));
        jPanel16.setPreferredSize(new java.awt.Dimension(187, 10));
        jPanel16.setLayout(new java.awt.BorderLayout());

        butBuy.setForeground(new java.awt.Color(51, 51, 255));
        butBuy.setText("Buy");
        butBuy.setPreferredSize(new java.awt.Dimension(51, 10));
        butBuy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butBuyActionPerformed(evt);
            }
        });
        jPanel16.add(butBuy, java.awt.BorderLayout.CENTER);

        jPanel13.add(jPanel16);

        jPanel17.setBackground(new java.awt.Color(255, 255, 255));
        jPanel17.setPreferredSize(new java.awt.Dimension(187, 20));

        jLabel11.setForeground(new java.awt.Color(0, 0, 255));
        jLabel11.setText("Total :");
        jPanel17.add(jLabel11);

        jLabel12.setText("0");
        jPanel17.add(jLabel12);

        jPanel13.add(jPanel17);

        jPanel8.add(jPanel13);

        jPanel7.add(jPanel8);

        jPanel3.add(jPanel7, java.awt.BorderLayout.SOUTH);

        jPanel9.setBackground(new java.awt.Color(255, 255, 255));
        jPanel9.setLayout(new java.awt.GridLayout(1, 0, 10, 0));

        jLabel6.setForeground(new java.awt.Color(0, 0, 255));
        jLabel6.setText("   Product List");
        jPanel9.add(jLabel6);

        jLabel7.setForeground(new java.awt.Color(0, 0, 255));
        jLabel7.setText("   Item List");
        jPanel9.add(jLabel7);

        jPanel3.add(jPanel9, java.awt.BorderLayout.CENTER);

        getContentPane().add(jPanel3, java.awt.BorderLayout.SOUTH);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtDateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDateActionPerformed
//kondisi ketika kita memngklik tabel
    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        try {
            //menentukan baris mana yang dipilih
            int row = jTable1.getSelectedRow();
            String tc = jTable1.getModel().getValueAt(row, 0).toString();
            //mengambil data dari ms product
            String query = "Select * From MsProduct Where ProductID ='"+tc+"'";
            //menjalankan query
            rs = kon.exec(query);
            rs.next();
            txtProductid.setText(rs.getString(1));
            txtProductname.setText(rs.getString(2));
            String a = rs.getString(4);
            String b = rs.getString(5);
            ImageIcon ic = new ImageIcon("Gambar/"+rs.getString(6));
            Image ig = ic.getImage().getScaledInstance( 187,170, java.awt.Image.SCALE_SMOOTH);
            lblImage.setIcon(new ImageIcon(ig));
            jml = Integer.parseInt(a);
            stk = Integer.parseInt(b);
        } catch (SQLException ex) {
            Logger.getLogger(DoTransactionForm.class.getName()).log(Level.SEVERE, null, ex);
        }
        spinQuantity.setValue(0);
            
       
            
        
    }//GEN-LAST:event_jTable1MouseClicked

    private void butRemoveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butRemoveActionPerformed
        // TODO add your handling code here:
        
        int tabelDipilih = jTable2.getSelectedRow();
        //validasi bila tidak ada data yang di delete
        if(tabelDipilih==-1){
           JOptionPane.showMessageDialog(rootPane, "No data selected !", "error",JOptionPane.ERROR_MESSAGE);
        }else{
            dm.removeRow(tabelDipilih);
            
        }
    }//GEN-LAST:event_butRemoveActionPerformed

    private void butAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butAddActionPerformed
        int index = jTable1.getSelectedRow();
        String coba = (String) cmbCustomer.getSelectedItem();
        //validasi user telah memilih table
        if ( index < 0 || index >= jTable1.getRowCount() ){
            JOptionPane.showMessageDialog(rootPane, "Please Select a product");
        }
        //validasi spinquantity tidak boleh kurang dari 0
        else if( Integer.parseInt( spinQuantity.getValue().toString()) <= 0 || Integer.parseInt( spinQuantity.getValue().toString()) > Integer.parseInt( jTable1.getValueAt(index, 4).toString()) ) {
            JOptionPane.showMessageDialog(rootPane, "Quantity Must be between 0 to stock");
        }

        //validasi apakah customer id telah dipilih
        else if(coba ==null){
            JOptionPane.showMessageDialog(null, "Customer ID must be choosen!");
        }else{
                //merubah jumlah stok menjadi integer
                int b = (Integer)spinQuantity.getValue();
                //menentukan besarnya array temp
                Object temp [] [] = new Object[data.length+1][3];
                //menginput nama kolom
                namakolom = new String[] {"product","price","quantity" };
                //menginput data ke dalam tabel
                for(int i = 0 ; i<data.length;i++){
                    for(int j = 0;j<3;j++){ 
                        temp [i][j] = data [i][j];

                    }
                }
                jml2 = jml2+(jml*b);
                String a = Integer.toString(jml2);
                temp [data.length][0]=txtProductid.getText();
                temp [data.length][1]=jml;
                String z = String.valueOf(spinQuantity.getValue());
                temp [data.length] [2]=z;
                data = temp;
                dm2.setDataVector(data, namakolom);
                jTable2.setModel(dm2);
                jLabel12.setText(a);
                
        }
        
    
    }//GEN-LAST:event_butAddActionPerformed

    private void butBuyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butBuyActionPerformed
        // TODO add your handling code here:
        
        String pi="";
        int quan =0;
        for(int i = 0; i<jTable2.getRowCount();i++){
            //menginsert query ke detail transaction
            kon.Update("INSERT INTO DetailTransaction (TransactionID, ProductID, Quantity) VALUES('"+txtTransaction.getText()+"','"+jTable2.getModel().getValueAt(i,0)+"','"+jTable2.getModel().getValueAt(i, 2)+"')");
            //kon.Update("UPDATE MsProduct SET Stock = '"+(Integer.valueOf(stk)-jTable2.getModel().getValueAt(i, 2))+"' WHERE ProductID = '"+jTable2.getModel().getValueAt(i,0)+"'");
            tabel();
            rs = kon.exec("SELECT * FROM HeaderTransaction");
        }
        //menginsert query ke header transaction
        kon.Update("INSERT INTO HeaderTransaction (TransactionID, EmployeeID, CustomerID, TransactionDate) VALUES('"+txtTransaction.getText()+"','"+txtEmployee.getText()+"','"+cmbCustomer.getSelectedItem()+"','"+txtDate.getText()+"')");
        rs = kon.exec("SELECT * FROM HeaderTransaction");
        //menghapus itemlist
        dm2.setNumRows(0);
        JOptionPane.showMessageDialog(rootPane, "Purchased");
    }//GEN-LAST:event_butBuyActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton butAdd;
    private javax.swing.JButton butBuy;
    private javax.swing.JButton butRemove;
    private javax.swing.JComboBox cmbCustomer;
    private javax.swing.JPanel gakguna;
    private javax.swing.JPanel gakguna2;
    private javax.swing.JPanel gakguna3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel16;
    private javax.swing.JPanel jPanel17;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JLabel lblImage;
    private javax.swing.JSpinner spinQuantity;
    private javax.swing.JTextField txtDate;
    private javax.swing.JTextField txtEmployee;
    private javax.swing.JTextField txtProductid;
    private javax.swing.JTextField txtProductname;
    private javax.swing.JTextField txtTransaction;
    // End of variables declaration//GEN-END:variables
}
